library(GenomicFeatures)
library(ComplexHeatmap)
library(GenomicRanges)
library(BSgenome.Hsapiens.UCSC.hg19)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(EnsDb.Hsapiens.v86)
library(GenomicFeatures)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(rtracklayer)
hg19_2Ome_coords <- read.table("RMBase_hg19_all_Nm_site.txt",header = F,sep = "\t")
colnames(hg19_2Ome_coords) <- c("chromosome","modStart","modEnd","modId","score","strand","modName","modType","supportNum","supportList","pubmedIds","geneName","geneType","region","sequence")
hg19_2Ome_granges <- makeGRangesFromDataFrame(hg19_2Ome_coords,keep.extra.columns = T,ignore.strand = F,seqnames.field = c("chromosome"),start.field = "modStart",end.field = "modEnd",strand.field = "strand",starts.in.df.are.0based = T)
double_mapping <- map(hg19_2Ome_granges,exonsBy(TxDb.Hsapiens.UCSC.hg19.knownGene))

